# Generated by Django 2.2 on 2019-06-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Enterprise', 'ent'), ('Individual', 'ind'), ('Free', 'free')], default='free', max_length=30),
        ),
    ]
