# Generated by Django 2.2 on 2019-06-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190607_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='strip_plan_id',
            new_name='stripe_plan_id',
        ),
    ]
