# Generated by Django 2.2 on 2019-06-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
